### ISSUE TITLE
Available Fields?

### ISSUE THREAD

**Issue by MACscr** [CloudAssessments/salesforce-web-to-lead#1]
Are the fields you have listed in your example the only fields available or is there a list somewhere? Thanks for making this great and simple script!

**Comment by linuxacademykurt** [comment]
@MACscr Sorry for taking so long to respond, I've been really busy on other projects.

The fields provided are simply the default Salesforce fields that everyone has.

However, you can create custom fields within Salesforce and use this library to submit those as well. Unfortunately, when you create a custom field in Salesforce (let's say you create a text box called `Referral Source`), the text box input name and id attribute for that field generated by Salesforce is completely random, e.g. `00N46000009SDY5`.

The only way to find out the ID of that field is to inspect your form in Salesforce in your browser and find the `name` attribute on the `<input>` element for that field.

Once you have that randomly generated name, you can use that as a key in the array when submitting to Salesforce.

For example:

```php
use CloudAssessments\Salesforce\WebToLead;

$form = new WebToLead();
$form
    ->setSalesforceAccountIdentifier('YourAccountID')  
    ->submit(                                          
        [                                              
            'first_name'      => 'John',
            'last_name'       => 'Doe',
            'email'           => 'johndoe@example.com',
            'phone'           => '555-123-4567',
            'company'         => 'Acme Inc.',
            'lead_source'     => 'Web-to-Lead',
             // Your new Referral Source field below
            '00N46000009SDY5 => 'https://example.com/referral-page',
        ]                                              
    );
```
